apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports: 
  - name: "redis-service"
    port: 6379  #we can make it any port but for simplicity
    targetPort: 6379
  selector:
    app: redis
