apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort   #since it is being accessed out
  ports: 
  - name: "result-service"
    port: 80  #we can make it any port but for simplicity
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
